### ISSUE TITLE
Navbar is outdated

### ISSUE THREAD

**Issue by difcsi** [difcsi/e5vosdosite#304]

**Comment by barnagoz** [comment]
Should also have a footer redesign

**Comment by difcsi** [comment]
> Should also have a footer redesign

Footer was adjusted in last commit

**Comment by barnagoz** [comment]
> > Should also have a footer redesign
> 
> Footer was adjusted in last commit

I've seen it, but I would recommend a redesign on that. (I will do it 😅)
